version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
