name: Install rust
description: Installs rust & caches dependencies
inputs:
  toolchain:
    description: Which toolchain to use
    required: false
    default: stable
  components:
    description: Space-separated list of components to Install
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Install rust
      shell: bash
      run: |
        rustup -V
        echo "::group::Install"
        rustup profile set minimal
        echo $INPUT_COMPONENTS | tr " " "\n" | xargs -I{} echo -n "-c {} " | xargs rustup toolchain install ${{ inputs.toolchain }} --allow-downgrade
        rustup override set ${{ inputs.toolchain }}
        echo "::endgroup::"
        rustc -V
        cargo -V
    - name: Cache index
      uses: actions/cache@v2
      with:
        # refresh every 2 weeks
        key: ${{ runner.os }}-cargo-index-$(expr $(date +%U) / 2)
        path: ~/.cargo/registry/index/
    - name: Cache
      uses: Swatinem/rust-cache@v1
