name: CI
on:
  - push
  - pull_request
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: fmt
        run: cargo fmt -- --check
      - name: clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cargo clippy --all-targets -- -D warnings
      - name: test
        env:
          FORCE_COLOR: true
        run: |
          cargo test --all-features
          cargo test
          cargo run --example example --all-features
          cargo run --example filter
