name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install rust
        run: rustup update
      - name: Fetch cache
        uses: Swatinem/rust-cache@v1
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Clippy (all features)
        run: cargo clippy --all-features --all-targets -- -D warnings
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install rust
        run: rustup update
      - name: Fetch cache
        uses: Swatinem/rust-cache@v1
      - name: Test
        run: cargo test
      - name: Test (all features)
        run: cargo test --all-features
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install rust
        run: rustup update
      - name: Rustfmt
        run: cargo fmt -- --check
  docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install rust
        run: rustup update
      - name: Check docs
        run: cargo doc --no-deps
      - name: Check docs (all features)
        run: cargo doc --no-deps --all-features
